#!/bin/bash

# Check for root
if [ "$EUID" -ne 0 ]
  then echo "I'm sorry $USER. I'm afraid I can't do that."
  exit
fi

# Who's running this thing?
me=$(who am i | awk '{print $1}')

# Backup motd configuration directory
cp -rf /etc/update-motd.d /etc/update-motd.bak

# Go into the motd dir
cd /etc/update-motd.d

# Trash unused files
rm 10-help-text 50-motd-news 80-esm 80-livepatch 95-hwe-eol

# Make the header file skip a line
echo echo > 00-header

# Add neofetch to the users' bashrc
echo "# Run neofetch" >> /home/$me/.bashrc
echo "/usr/local/sbin/neofetch" >> /home/$me/.bashrc

